<a href="https://colab.research.google.com/github/NandiniBasdwar7/concise/blob/main/13DAY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

data = {'value': [10, 12, 8, 15, 20, 18, 25, 22]}
dates = pd.to_datetime(['2025-01-01 09:00', '2025-01-01 10:00', '2025-01-01 11:00',
                        '2025-01-02 09:00', '2025-01-02 10:00', '2025-01-02 11:00',
                        '2025-01-03 09:00', '2025-01-03 10:00'])
df = pd.DataFrame(data, index=dates)


df_daily_mean = df.resample('D').mean()
print( df_daily_mean)

df_ffill=df.resample('D').ffill()
print(df_ffill)

                value
2025-01-01  10.000000
2025-01-02  17.666667
2025-01-03  23.500000
            value
2025-01-01    NaN
2025-01-02    8.0
2025-01-03   18.0

In [11]:
#Sorting and slicing by date in Pandas DataFrames are common operations.
data={
    'date':['2023-01-01','2023-01-05','2023-01-03','2023-01-04','2023-01-02'],
    'value':[10,30,20,40,50]
}
df=pd.DataFrame(data)
df['date']=pd.to_datetime(df['date'])
df_sort=df.sort_values(by='date')
df_sort

df_sort_asc=df_sort.sort_values(by='date',ascending=False)
df_sort_asc

        date  value
1 2023-01-05     30
3 2023-01-04     40
2 2023-01-03     20
4 2023-01-02     50
0 2023-01-01     10

In [39]:
#Slicing by date
data={
    'date':['2023-01-01','2023-01-05','2023-01-03','2023-01-04','2023-01-02'],
    'value':[10,30,20,40,50]
}
df=pd.DataFrame(data)
df['date']=pd.to_datetime(df['date'])
df.set_index('date',inplace=True)


# Selecting data for a specific date
print(df.loc['2023-01-01'])

# Selecting data for a specific month
print(df.loc['2023-01'])

value    10
Name: 2023-01-01 00:00:00, dtype: int64
            value
date
2023-01-01     10
2023-01-05     30
2023-01-03     20
2023-01-04     40
2023-01-02     50

In [40]:
#Exporting to CSV:-The DataFrame.to_csv() method is used to save a DataFrame as a CSV file.
data = {'col1': [1, 2, 3], 'col2': ['A', 'B', 'C']}
df = pd.DataFrame(data)

# Export to CSV
df.to_csv('output.csv', index=False)

In [42]:
df.to_parquet('output.parquet', engine='pyarrow')
df.to_parquet

<bound method DataFrame.to_parquet of    col1 col2
0     1    A
1     2    B
2     3    C>

In [92]:
data = {'value': [10, 12, 8, 15, 20, 18, 25, 22]}
dates = pd.to_datetime(['2025-01-01 09:00', '2025-01-01 10:00', '2025-01-01 11:00',
                        '2025-01-02 09:00', '2025-01-02 10:00', '2025-01-02 11:00',
                        '2025-01-03 09:00', '2025-01-03 10:00'])
df = pd.DataFrame(data)

In [93]:
from datetime import date
#Parse date column as datetime.
df['date'] = pd.to_datetime(dates)
df['date']

0   2025-01-01 09:00:00
1   2025-01-01 10:00:00
2   2025-01-01 11:00:00
3   2025-01-02 09:00:00
4   2025-01-02 10:00:00
5   2025-01-02 11:00:00
6   2025-01-03 09:00:00
7   2025-01-03 10:00:00
Name: date, dtype: datetime64[ns]

In [96]:
#Resample data to weekly aggregates.
df.set_index('date', inplace=True)
weekly=df.resample('W').sum()
weekly.reset_index()

        date  value
0 2025-01-05    130

In [97]:
#Calculate % change week over week.
weekly['%change']=weekly['value'].pct_change()
weekly

            value  %change
date
2025-01-05    130      NaN

In [189]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# Set random seed for reproducibility
random.seed(42)
np.random.seed(42)

# Generate 150 random dates
start_date = datetime(2023, 1, 1)
date_list = [start_date + timedelta(days=i) for i in range(150)]
random_dates = random.choices(date_list, k=150)

# --- WEATHER DATASET ---
weather_data = {
    'date': [d.strftime('%Y-%m-%d') if i % 10 != 0 else d.strftime('%d/%m/%Y') for i, d in enumerate(random_dates)],
    'Temp': [round(np.random.uniform(15, 40), 1) if i % 8 != 0 else 'hot' for i in range(150)],
    'humidity(%)': [np.random.randint(20, 100) if i % 7 != 0 else np.nan for i in range(150)],
    'wind_speed': [round(np.random.uniform(0, 20), 2) if i % 5 != 0 else "fast" for i in range(150)],
    'city': [random.choice(['New York', 'Los Angeles', 'Chicago', np.nan, '']) for _ in range(150)],
}

weather_df = pd.DataFrame(weather_data)

# Add some duplicate rows
weather_df = pd.concat([weather_df, weather_df.iloc[0:5]], ignore_index=True)

# --- SALES DATASET ---
sales_data = {
    'date': [d.strftime('%Y-%m-%d') if i % 6 != 0 else d.strftime('%B %d, %Y') for i, d in enumerate(random_dates)],
    'sales_amount': [round(np.random.uniform(1000, 10000), 2) if i % 10 != 0 else 'high' for i in range(150)],
    'product_id': [random.choice(['P001', 'P002', 'P003', np.nan, 'p001']) for _ in range(150)],
    'units_sold': [np.random.randint(1, 50) if i % 9 != 0 else None for i in range(150)],
    'store_location': [random.choice(['New York', 'Chicago', 'Houston', '', np.nan]) for _ in range(150)],
}

sales_df = pd.DataFrame(sales_data)

# Add some duplicate rows
sales_df = pd.concat([sales_df, sales_df.iloc[2:4]], ignore_index=True)

# --- SAVE TO CSV FILES ---
weather_df.to_csv("weather.csv", index=False)
sales_df.to_csv("sales.csv", index=False)

print("Generated messy 'weather.csv' and 'sales.csv' with 150+ rows each.")

Generated messy 'weather.csv' and 'sales.csv' with 150+ rows each.

In [190]:
sales=pd.read_csv('/content/sales.csv')

In [191]:
sales.head(10)

             date sales_amount product_id  units_sold store_location
0  April 06, 2023         high       P003         NaN            NaN
1      2023-01-04      6727.63       P003        28.0            NaN
2      2023-02-11      8208.54       P002        36.0       New York
3      2023-02-03      7094.52        NaN        26.0        Houston
4      2023-04-21       6160.3       p001         8.0        Houston
5      2023-04-12       2156.5       P003        28.0        Chicago
6    May 14, 2023      8300.84       p001        28.0            NaN
7      2023-01-14      8385.76       p001        37.0            NaN
8      2023-03-05      6633.46       P001        41.0            NaN
9      2023-01-05      8383.84       p001         NaN        Houston

In [192]:
weather=pd.read_csv('/content/weather.csv')

In [193]:
weather

           date  Temp  humidity(%) wind_speed      city
0    06/04/2023   hot          NaN       fast   Chicago
1    2023-01-04  24.4         56.0      15.37       NaN
2    2023-02-11  38.8         70.0       0.87       NaN
3    2023-02-03  33.3         63.0      19.89       NaN
4    2023-04-21  30.0         43.0        9.4  New York
..          ...   ...          ...        ...       ...
150  06/04/2023   hot          NaN       fast   Chicago
151  2023-01-04  24.4         56.0      15.37       NaN
152  2023-02-11  38.8         70.0       0.87       NaN
153  2023-02-03  33.3         63.0      19.89       NaN
154  2023-04-21  30.0         43.0        9.4  New York

[155 rows x 5 columns]

In [194]:
sales.shape

weather.shape

(155, 5)

In [195]:
sales[sales.duplicated()].drop_duplicates()

           date sales_amount product_id  units_sold store_location
150  2023-02-11      8208.54       P002        36.0       New York
151  2023-02-03      7094.52        NaN        26.0        Houston

In [196]:
sales.shape

(152, 5)

In [197]:
sales.isna().sum()

date               0
sales_amount       0
product_id        24
units_sold        17
store_location    74
dtype: int64

In [198]:
sales=sales.drop(columns=['store_location'])

In [199]:
sales

               date sales_amount product_id  units_sold
0    April 06, 2023         high       P003         NaN
1        2023-01-04      6727.63       P003        28.0
2        2023-02-11      8208.54       P002        36.0
3        2023-02-03      7094.52        NaN        26.0
4        2023-04-21       6160.3       p001         8.0
..              ...          ...        ...         ...
147      2023-04-20       4550.7       p001        34.0
148      2023-01-31       1960.8       p001         6.0
149      2023-02-16      4020.94       P003         2.0
150      2023-02-11      8208.54       P002        36.0
151      2023-02-03      7094.52        NaN        26.0

[152 rows x 4 columns]

In [200]:
sales.fillna(method='ffill',inplace=True)
sales

/tmp/ipython-input-200-2747855204.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  sales.fillna(method='ffill',inplace=True)

               date sales_amount product_id  units_sold
0    April 06, 2023         high       P003         NaN
1        2023-01-04      6727.63       P003        28.0
2        2023-02-11      8208.54       P002        36.0
3        2023-02-03      7094.52       P002        26.0
4        2023-04-21       6160.3       p001         8.0
..              ...          ...        ...         ...
147      2023-04-20       4550.7       p001        34.0
148      2023-01-31       1960.8       p001         6.0
149      2023-02-16      4020.94       P003         2.0
150      2023-02-11      8208.54       P002        36.0
151      2023-02-03      7094.52       P002        26.0

[152 rows x 4 columns]

In [201]:
sales.isna().sum()

date            0
sales_amount    0
product_id      0
units_sold      1
dtype: int64

In [202]:
weather.isna().sum()

date            0
Temp            0
humidity(%)    23
wind_speed      0
city           63
dtype: int64

In [212]:
weather['city'].unique()

array(['Chicago', nan, 'New York', 'Los Angeles'], dtype=object)

In [204]:
#fillna
weather['city'].mode()[0]

'New York'

In [209]:
weather['city']

0       Chicago
1           NaN
2           NaN
3           NaN
4      New York
         ...
150     Chicago
151         NaN
152         NaN
153         NaN
154    New York
Name: city, Length: 155, dtype: object

In [210]:
weather['humidity(%)'].fillna(weather['humidity(%)'].mean(),inplace=True)
weather['humidity(%)']

0      57.25
1      56.00
2      70.00
3      63.00
4      43.00
       ...
150    57.25
151    56.00
152    70.00
153    63.00
154    43.00
Name: humidity(%), Length: 155, dtype: float64

In [211]:
weather.isna().sum()

date            0
Temp            0
humidity(%)     0
wind_speed      0
city           63
dtype: int64